# Generated by Django 5.1.2 on 2024-11-06 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='last_request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
